class TopMenuItem {
  final String id;
  final String name;
  final String imageUrl;

  /// Number of orders containing this item
  final int soldCount;

  /// Total revenue generated by this item
  final double revenue;

  /// Sales percentage used for progress bars
  /// Example: 0.75 = 75%
  final double percentage;

  const TopMenuItem({
    required this.id,
    required this.name,
    this.imageUrl = '',
    required this.soldCount,
    required this.revenue,
    required this.percentage,
  });

  TopMenuItem copyWith({
    String? id,
    String? name,
    String? imageUrl,
    int? soldCount,
    double? revenue,
    double? percentage,
  }) {
    return TopMenuItem(
      id: id ?? this.id,
      name: name ?? this.name,
      imageUrl: imageUrl ?? this.imageUrl,
      soldCount: soldCount ?? this.soldCount,
      revenue: revenue ?? this.revenue,
      percentage: percentage ?? this.percentage,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'imageUrl': imageUrl,
      'soldCount': soldCount,
      'revenue': revenue,
      'percentage': percentage,
    };
  }

  factory TopMenuItem.fromMap(Map<String, dynamic> map) {
    return TopMenuItem(
      id: map['id'] ?? '',
      name: map['name'] ?? '',
      imageUrl: map['imageUrl'] ?? '',
      soldCount: map['soldCount'] ?? 0,
      revenue: (map['revenue'] ?? 0).toDouble(),
      percentage: (map['percentage'] ?? 0).toDouble(),
    );
  }
}
