// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmej5oUKrxS66IltKwnnTaTkyeApyfA7o',
    appId: '1:204881672545:web:5ac419a0acc00afab5ad20',
    messagingSenderId: '204881672545',
    projectId: 'smart-canteen-e4f83',
    authDomain: 'smart-canteen-e4f83.firebaseapp.com',
    storageBucket: 'smart-canteen-e4f83.firebasestorage.app',
    measurementId: 'G-5D76BR210L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5HYnLYeOo680CSFVzCeYndt_LtLx4HDc',
    appId: '1:204881672545:android:d24b878d0d61370eb5ad20',
    messagingSenderId: '204881672545',
    projectId: 'smart-canteen-e4f83',
    storageBucket: 'smart-canteen-e4f83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnUIZS6Y4DdfABiNuKRAOnG0BqBJVt_b0',
    appId: '1:204881672545:ios:21227b80eb4707e0b5ad20',
    messagingSenderId: '204881672545',
    projectId: 'smart-canteen-e4f83',
    storageBucket: 'smart-canteen-e4f83.firebasestorage.app',
    iosBundleId: 'com.example.smartCanteenShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnUIZS6Y4DdfABiNuKRAOnG0BqBJVt_b0',
    appId: '1:204881672545:ios:21227b80eb4707e0b5ad20',
    messagingSenderId: '204881672545',
    projectId: 'smart-canteen-e4f83',
    storageBucket: 'smart-canteen-e4f83.firebasestorage.app',
    iosBundleId: 'com.example.smartCanteenShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmej5oUKrxS66IltKwnnTaTkyeApyfA7o',
    appId: '1:204881672545:web:b26acaf4fad00ddbb5ad20',
    messagingSenderId: '204881672545',
    projectId: 'smart-canteen-e4f83',
    authDomain: 'smart-canteen-e4f83.firebaseapp.com',
    storageBucket: 'smart-canteen-e4f83.firebasestorage.app',
    measurementId: 'G-VPKZYKE96N',
  );
}
